controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_vel:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_vel:
  ros__parameters:
    joints:
      - Back_left2_joint
      - Back_right2_joint
      - Front_left2_joint
      - Front_right2_joint
    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity
      - effort
    